//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTypeSupportedMetaData
    {
        public int AssetSupportedMetaDataID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> MetaDataID { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual MetaData MetaData { get; set; }
    }
}
